### ISSUE TITLE
The input is hidden for user when using craft columns or small screen sizes

### ISSUE THREAD

**Issue by kevinmu17** [sebastian-lenz/craft-linkfield#173]
The input of the linkfield is not visible when using some screen sizes or the columns editor from craft.

<img width="366" alt="Screenshot 2021-10-07 at 10 22 41" src="https://user-images.githubusercontent.com/8747373/136347299-1241390e-5d7e-4513-bd4c-2a85e9055fdd.png">

```css
.linkfield--field {
    display: flex;
    flex-flow: row nowrap;
    width: 100%;
    align-items: center;
}
```
The issue is the nowrap on on the flex-flow. this should be `flex-flow: row wrap;` or depending on the column width of craft (but i tested the above, works on all scenario's): 

```css
.field.width-25 .linkfield--field {
     flex-flow: row wrap;
}
```
